CREATE
  TABLE ATTAQUE
  (
    NOM_ATT  VARCHAR(30),
    TYPE_ATT VARCHAR(30),
    PP       DECIMAL(3,0),
    DEGATS   DECIMAL(3,0),
    PREC     DECIMAL(3,0),
    CONSTRAINT PK_ATT PRIMARY KEY (NOM_ATT)) ;

CREATE
  TABLE CONNAIT
  (
    NUM_P   DECIMAL(3,0),
    NOM_ATT VARCHAR(30),
    CONSTRAINT PK_CONNAIT PRIMARY KEY (NUM_P, NOM_ATT),
    CONSTRAINT FK_POKE_CONNAIT FOREIGN KEY (NUM_P) REFERENCES 
    POKEMON (NUM_P),
    CONSTRAINT FK_ATT_CONNUE FOREIGN KEY (NOM_ATT) REFERENCES 
    ATTAQUE (NOM_ATT)
 )
  ;

CREATE
  TABLE ELEVEUR
  (
    NUM_E DECIMAL(3,0),
    NOM_E VARCHAR(30),
    CONSTRAINT PK_ELEV PRIMARY KEY (NUM_E)
 );

CREATE
  TABLE POKEMON
  (
    NUM_P       DECIMAL(3,0),
    NOM_P       VARCHAR(30),
    TYPE_P      VARCHAR(30),
    CARACTERE   VARCHAR(30),
    COULEUR     VARCHAR(20),
    ELEVEUR     DECIMAL(3,0),
    EVOLUTION   VARCHAR(30),
    PREVOLUTION VARCHAR(30),
    CRI         VARCHAR(50),
    EXP         DECIMAL(5,0),
    NIV         DECIMAL(3,0),
    VIE_MAX     DECIMAL(4,0),
    VIE         DECIMAL(4,0),
    CONSTRAINT PK_POKE PRIMARY KEY (NUM_P),
    CONSTRAINT FK_POKE_ELEV FOREIGN KEY (ELEVEUR) REFERENCES 
    ELEVEUR (NUM_E)
 );

CREATE
  TABLE POSSEDE
  (
    NUM_E DECIMAL(3,0),
    NOM_E VARCHAR(30),
    NUM_P DECIMAL(3,0),
    NOM_P VARCHAR(30),
    CONSTRAINT FK_DRESS_POSSEDE FOREIGN KEY (NUM_E) REFERENCES 
    ELEVEUR (NUM_E) ,
    CONSTRAINT FK_POKE_APPARTIENT FOREIGN KEY (NUM_P) REFERENCES 
    POKEMON (NUM_P) 
 );
